"""deals.number: настоящая последовательность

Колонка была объявлена с autoincrement=True, но в SQLAlchemy этот флаг
действует ТОЛЬКО на первичный ключ, а первичный здесь id. В результате
number оставалась NOT NULL без значения по умолчанию, и создание сделки
падало с NotNullViolationError — то есть первая же P2P-покупка не прошла бы.

Переводим на GENERATED BY DEFAULT AS IDENTITY: PostgreSQL сам выдаёт
следующий номер, при этом явно заданное значение тоже принимается.

Revision ID: c6d7e8f9a0b1
Revises: b5c6d7e8f9a0
Create Date: 2026-09-15
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c6d7e8f9a0b1'
down_revision: Union[str, None] = 'b5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE deals ALTER COLUMN number ADD GENERATED BY DEFAULT AS IDENTITY")


def downgrade() -> None:
    op.execute("ALTER TABLE deals ALTER COLUMN number DROP IDENTITY IF EXISTS")
